name: Build Repo Listing

on:
  push:
    branches: [ main ]
  release:
    types: [published, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Repo Listing
        uses: vrchat-community/package-list-action@v1
        with:
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          package-name: com.yuki-2525.unityeditorassetbrowser

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Website
